name: Run Instagram Comment Count Script

on:
  schedule:
    - cron: '30 5 * * *'  # Runs at 11:00 AM IST
    - cron: '30 11 * * *'  # Runs at 5:00 PM IST
  workflow_dispatch:  # Allows manual run

jobs:
  run-final-insta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client requests

      - name: Run final_insta.py
        run: |
          python final_insta.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials/creds.json

      - name: Show completion
        run: echo "Script executed successfully."
